#config_version=6

# Mode for paying out 50 for non-lit inlanes

mode:
  start_events:
    - ball_starting # starts on a new ball
    - resetLitInlanes # start this mode when both lanes have been lit and hit
  priority: 110
  stop_events: leftStars_complete, mbFail # if the left stars are lit stop this mode

event_player:
  s_inLane_L_active: pay50
  s_inLane_R_active: pay50
