#config_version=6

# Because of a bad bit shift chip, all of the lights are strung together on chain 1

lights:
  l_soul_L:
    number: 1-0-0
    type: grb
    subtype: led
    tags: inserts, soul_lanes
  l_soul_U:
    number: 1-0-1
    type: grb
    subtype: led
    tags: inserts, soul_lanes
  l_soul_O:
    number: 1-0-2
    type: grb
    subtype: led
    tags: inserts, soul_lanes
  l_soul_S:
    number: 1-0-3
    type: grb
    subtype: led
    tags: inserts, soul_lanes
  l_lane_L_6:
    number: 1-0-4
    type: grb
    subtype: led
    tags: inserts
  l_lane_L_5:
    number: 1-0-5
    type: grb
    subtype: led
    tags: inserts
  l_star_1:
    number: 1-0-6
    type: grb
    subtype: led
    tags: inserts
  l_lane_L_4:
    number: 1-0-7
    type: grb
    subtype: led
    tags: inserts
  l_lane_L_3:
    number: 1-0-8
    type: grb
    subtype: led
    tags: inserts
  l_star_2:
    number: 1-0-9
    type: grb
    subtype: led
    tags: inserts
  l_lane_L_2:
    number: 1-0-10
    type: grb
    subtype: led
    tags: inserts
  l_lane_L_1:
    number: 1-0-11
    type: grb
    subtype: led
    tags: inserts
  l_dash_L:
    number: 1-0-12
    type: grb
    subtype: led
    tags: inserts
  l_outLane_L:
    number: 1-0-13
    type: grb
    subtype: led
    tags: inserts
  l_inLane_L:
    number: 1-0-14
    type: grb
    subtype: led
    tags: inserts
  l_bonus_4000:
    number: 1-0-15
    type: grb
    subtype: led
    tags: inserts
  l_bonus_5000:
    number: 1-0-16
    type: grb
    subtype: led
    tags: inserts
  l_bonus_10000:
    number: 1-0-17
    type: grb
    subtype: led
    tags: inserts
  l_bonus_9000:
    number: 1-0-18
    type: grb
    subtype: led
    tags: inserts
  l_4x:
    number: 1-0-19
    type: grb
    subtype: led
    tags: inserts
  l_3x:
    number: 1-0-20
    type: grb
    subtype: led
    tags: inserts
  l_2x:
    number: 1-0-21
    type: grb
    subtype: led
    tags: inserts
  l_bonus_3000:
    number: 1-0-22
    type: grb
    subtype: led
    tags: inserts
  l_cup_sling:
    number: 1-0-23
    type: grb
    subtype: led
    tags: inserts
  l_bonus_2000:
    number: 1-0-24
    type: grb
    subtype: led
    tags: inserts
  l_bonus_1000:
    number: 1-0-25
    type: grb
    subtype: led
    tags: inserts
  l_shootAgain:
    number: 1-0-26
    type: grb
    subtype: led
    tags: inserts
  l_bonus_6000:
    number: 1-0-27
    type: grb
    subtype: led
    tags: inserts
  l_bonus_7000:
    number: 1-0-28
    type: grb
    subtype: led
    tags: inserts
  l_bonus_8000:
    number: 1-0-29
    type: grb
    subtype: led
    tags: inserts
  l_mug_sling:
    number: 1-0-30
    type: grb
    subtype: led
    tags: inserts
  l_inLane_R:
    number: 1-0-31
    type: grb
    subtype: led
    tags: inserts
  l_outLane_R:
    number: 1-0-32
    type: grb
    subtype: led
    tags: inserts
  l_dash_R:
    number: 1-0-33
    type: grb
    subtype: led
    tags: inserts
  l_star_3:
    number: 1-0-34
    type: grb
    subtype: led
    tags: inserts
  l_perdition_1:
    number: 1-0-35
    type: grb
    subtype: led
    tags: inserts
  l_perdition_2:
    number: 1-0-36
    type: grb
    subtype: led
    tags: inserts
  l_perdition_3:
    number: 1-0-37
    type: grb
    subtype: led
    tags: inserts
  l_extraBall:
    number: 1-0-38
    type: grb
    subtype: led
    tags: inserts
  l_popBumper_3:
    number: 1-0-39
    type: grb
    subtype: led
    tags: inserts
  l_popBumper_2:
    number: 1-0-40
    type: grb
    subtype: led
    tags: inserts
  l_popBumper_1:
    number: 1-0-41
    type: grb
    subtype: led
    tags: inserts
  l_standUp_3:
    number: 1-0-42
    type: grb
    subtype: led
    tags: inserts
  l_standUp_2:
    number: 1-0-43
    type: grb
    subtype: led
    tags: inserts
  l_standUp_1:
    number: 1-0-44
    type: grb
    subtype: led
    tags: inserts
  l_special7:
    number: 1-0-45
    type: grb
    subtype: led
    tags: inserts

  l_gi0:
    number: 1-0-46
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi1:
    number: 1-0-48
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi2:
    number: 1-0-49
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi3:
    number: 1-0-51
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi4:
    number: 1-0-52
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi5:
    number: 1-0-54
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi6:
    number: 1-0-55
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi7:
    number: 1-0-56
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi8:
    number: 1-0-57
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi9:
    number:  1-0-58
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi10:
    number: 1-0-59
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi11:
    number: 1-0-60
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi12:
    number: 1-0-61
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi13:
    number: 1-0-62
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi14:
    number: 1-0-63
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi15:
    number: 1-0-64
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi16:
    number: 1-0-65
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi17:
    number: 1-0-66
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi18:
    number: 1-0-67
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi19:
    number: 1-0-68
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi20:
    number: 1-0-69
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi21:
    number: 1-0-70
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi22:
    number: 1-0-71
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi23:
    number: 1-0-72
    subtype: led
    tags: gi
    fade_ms: 500
  l_gi24:
    number: 1-0-73
    subtype: led
    tags: gi
    fade_ms: 500
