#config_version=6

# Mode to pay out 50 for dash hits

mode:
  start_events:
    - dash_complete
    - ball_starting
  stop_events: standUps_complete
  priority: 110

event_player:
  s_dash_L_active: pay50
  s_dash_R_active: pay50
