#config_version=6

# This is a mode that continuously drops the perdition post and tries to clear the perdition lane for the multiball

mode:
  start_events: timer_perditionPost_timer_started # start with achieving the multiball
  stop_events: mbFail, s_trough1_active{current_player.perditionBallSaveOn==0} # end when a ball drains and the ball saver has expired
  priority: 220
  restart_on_next_ball: true

timers:
  settle_timer:
    direction: down
    start_value: 3
    end_value: 0
    tick_interval: 100ms
    debug: true
    control_events:
      - action: restart
        event: s_perdition_kicker_active
###############################################################################################
#                                      PLAYERS                                                #
###############################################################################################

variable_player:
  s_perdition_kicker_active:
    perdition_value:
      int: 0
      action: set
    advance_perdition_value:
      int: 0
      action: set

event_player:
  s_perdition_kicker_active: clearLane

coil_player:
  clearLane: c_perdition_post_down
  timer_settle_timer_complete: c_perdition_kicker

show_player:
  s_perdition_kicker_active:
    perdition0: play
    perdition1on: stop
    perdition2on: stop
    perdition3On: stop
